"""Write table.go: Rich's cell-width table (the latest Unicode version Rich ships), which
cells.Width uses so widths agree with Python pqx (Rich's cell_len).

    <python with rich> go/internal/cells/gen_table.py && gofmt -w go/internal/cells/table.go

Rich's tables are generated from the wcwidth project's data (both MIT licensed).
"""
import os

from rich._unicode_data import load

t = load("latest")
here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "table.go"), "w") as f:
    f.write("// Code generated by gen_table.py from Rich's cell table (Unicode %s); DO NOT EDIT.\n\n" % t.unicode_version)
    f.write("package cells\n\n")
    f.write("// unicodeVersion is the Unicode version of the table.\n")
    f.write('const unicodeVersion = "%s"\n\n' % t.unicode_version)
    f.write("// widthTable: ranges of code points [lo, hi] and their width (0, 1 or 2), sorted.\n")
    f.write("var widthTable = [...]struct {\n\tlo, hi rune\n\tw      int8\n}{\n")
    for lo, hi, w in t.widths:
        f.write("\t{0x%X, 0x%X, %d},\n" % (lo, hi, w))
    f.write("}\n\n")
    f.write("// narrowToWide: characters a VS16 (U+FE0F) after them makes two cells wide.\n")
    f.write("var narrowToWide = map[rune]bool{\n")
    for c in sorted(t.narrow_to_wide):
        f.write("\t0x%X: true,\n" % ord(c))
    f.write("}\n")
